import React,{useEffect,useState} from 'react';
import {Users,Plus,Link,ArrowLeft,Check} from 'lucide-react';
import SpeechInput from './SpeechInput';
import TravelInfo from './TravelInfo';
const KEY='wolgye-group-memberships-v1';
function stored(){try{return JSON.parse(localStorage.getItem(KEY))||{};}catch{return {};}}
export default function Groups({nickname,userLocation,locating,locationError,onLocate}) {
  const [memberships,setMemberships]=useState(stored),[group,setGroup]=useState(null),[active,setActive]=useState(''),[name,setName]=useState(''),[nick,setNick]=useState(nickname),[code,setCode]=useState(()=>new URLSearchParams(location.search).get('group')||''),[condition,setCondition]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  async function api(path,method='GET',body,token){
    const r=await fetch('/api/groups'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(65000)});
    if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('모임 서버에 연결되지 않았어요. 잠시 후 다시 시도해 주세요.');
    const d=await r.json();if(!r.ok)throw new Error(d.error||'요청을 완료하지 못했어요.');return d;
  }
  const [spinning,setSpinning]=useState(false),[secret,setSecret]=useState(false);
  async function finalize(mode){await perform(async()=>{if(mode==='roulette')setSpinning(true);const d=await api('/'+active+'/finalize','POST',{mode},mine.token);setGroup(d.group);if(mode==='roulette')setTimeout(()=>setSpinning(false),2200);});}
  const mine=memberships[active];
  const me=group?.members.find(m=>m.id===mine?.memberId);
  function accept(d){
    const next={...memberships,[d.group.id]:{token:d.token,memberId:d.memberId,name:d.group.name}};
    localStorage.setItem(KEY,JSON.stringify(next));setMemberships(next);setActive(d.group.id);setGroup(d.group);setCondition('');setError('');
  }
  async function perform(work){setBusy(true);setError('');setMessage('');try{await work();}catch(e){setSpinning(false);setError(e.name==='TimeoutError'?'응답이 지연되고 있어요. 다시 시도해 주세요.':e.message);}finally{setBusy(false);}}
  async function open(id){await perform(async()=>{const d=await api('/'+id,'GET',undefined,memberships[id].token);setActive(id);setGroup(d.group);const mineNow=d.group.members.find(m=>m.id===memberships[id].memberId);setCondition(mineNow?.condition||'');setSecret(!!mineNow?.private);});}
  useEffect(()=>{
    if(!active||!mine||busy)return;
    let stopped=false,pending=false;
    const timer=setInterval(async()=>{if(pending)return;pending=true;try{const d=await api('/'+active,'GET',undefined,mine.token);if(!stopped){setGroup(d.group);setError('');}}catch(e){if(!stopped)setError(e.message);}finally{pending=false;}},3000);
    return()=>{stopped=true;clearInterval(timer);};
  },[active,mine?.token,busy]);
  const ready=group?.members.every(m=>m.condition);
  return <div className="groups-page">
    <div className="page-heading"><div className="badge-title"><h1><mark className="hl">모임</mark></h1><span className="title-badge">{Object.keys(memberships).length?`${Object.keys(memberships).length}개 참여 중`:'아직 모임 없음'}</span></div></div>
    {error&&<div className="notice" role="alert">{error}</div>}{message&&<p role="status" className="notice">{message}</p>}
    {!group?<>
      <label>모임에서 사용할 닉네임<input value={nick} maxLength={30} onChange={e=>setNick(e.target.value)} /></label>
      <div className="group-grid">
        <form className="group-card" onSubmit={e=>{e.preventDefault();perform(async()=>accept(await api('/','POST',{name,nickname:nick})));}}><h2>새 모임</h2><label>모임 이름<input value={name} onChange={e=>setName(e.target.value)} required maxLength={40}/></label><button disabled={busy||!nick.trim()} className="button lime"><Plus size={18}/>모임 만들기</button></form>
        <form className="group-card" onSubmit={e=>{e.preventDefault();const id=code.trim().toUpperCase();if(memberships[id])open(id);else perform(async()=>accept(await api('/'+encodeURIComponent(id)+'/join','POST',{nickname:nick})));}}><h2>초대받았나요?</h2><label>초대 코드<input value={code} onChange={e=>setCode(e.target.value)} required maxLength={12}/></label><button disabled={busy||!nick.trim()} className="button outline"><Users size={18}/>모임 참여</button></form>
      </div><h2 className="section-title">내 모임</h2><div className="group-grid">{Object.entries(memberships).map(([id,m])=><button className="group-card" key={id} disabled={busy} onClick={()=>open(id)}><h3>{m.name}</h3><small>{id}</small></button>)}</div>
      <p className="muted">공유 주소에서 만든 모임은 초대 링크나 코드로 함께 참여할 수 있어요. 모임 코드를 아는 사람에게 참가 내용이 공유됩니다.</p>
    </>:<section className="group-workspace">
      <button className="text-link" onClick={()=>{setGroup(null);setActive('');setError('');}}><ArrowLeft size={18}/>모임 목록</button>
      <div className="section-heading"><h2>{group.name}</h2><button className="button outline" onClick={()=>perform(async()=>{const url=new URL(location.href);url.search='';url.searchParams.set('group',group.id);await navigator.clipboard.writeText(url.toString());setMessage('초대 링크를 복사했어요. 받는 사람도 이 서버에 접속할 수 있어야 합니다.');})}><Link size={18}/>초대 링크 복사</button></div>
      <p>초대 코드 <strong>{group.id}</strong> · {group.members.length}명</p><button className="text-link" onClick={onLocate}>{locating?'위치 확인 중…':userLocation?'현재 위치 다시 확인':'현재 위치로 거리 보기'}</button>{locationError&&<p role="alert">{locationError}</p>}
      <form onSubmit={e=>{e.preventDefault();perform(async()=>{const d=await api('/'+active+'/condition','PUT',{condition,private:secret},mine.token);setGroup(d.group);setMessage('내 조건을 저장했어요. 조건이 바뀌면 이전 후보와 투표는 초기화됩니다.');});}}><label>{me?.name}님의 조건<textarea required maxLength={240} value={condition} onChange={e=>setCondition(e.target.value)} placeholder="원하는 조건을 자유롭게 적어주세요."/></label><SpeechInput value={condition} onChange={setCondition} maxLength={240} disabled={busy}/><label className="secret-check"><input type="checkbox" checked={secret} onChange={e=>setSecret(e.target.checked)}/><span>비밀로 하기 <small>다른 참가자에게 조건 내용이 보이지 않아요. 추천에는 그대로 쓰여요.</small></span></label><button disabled={busy} className="button dark">내 조건 저장</button></form>
      <div className="group-members">{group.members.map(m=><div className="member-row" key={m.id}><b>{m.name}{m.id===mine.memberId?' (나)':''}</b><p className={m.private&&m.id!==mine.memberId?'muted':''}>{m.private&&m.id!==mine.memberId?'🔒 비밀 조건':m.condition?(m.private?`🔒 ${m.condition}`:m.condition):'조건 입력 중…'}</p></div>)}</div>
      {!!group.suggestions?.length&&<section className="group-suggestions"><h3>소식에서 모은 가게</h3><p className="muted">제안된 가게는 조건에 맞으면 다음 추천에서 우선 살펴봐요. 진행 중인 투표 후보는 바뀌지 않아요.</p><div className="group-suggestion-list">{group.suggestions.map(s=><span key={s.placeId}>{s.placeName} <small>· {s.by} 제안</small></span>)}</div>{group.candidates&&!group.decision&&!Object.values(group.votes||{}).some(v=>v.length)&&group.ownerId===mine.memberId&&<button className="button outline" disabled={busy||!ready} onClick={()=>perform(async()=>{const d=await api('/'+active+'/recommend','POST',{},mine.token);setGroup(d.group);})}>제안 반영해 후보 다시 찾기</button>}</section>}
      {!group.candidates&&(group.ownerId===mine.memberId?<button className="button lime" disabled={busy||!ready} onClick={()=>perform(async()=>{const d=await api('/'+active+'/recommend','POST',{},mine.token);setGroup(d.group);})}>{busy?'처리 중…':'함께 갈 후보 찾기'}</button>:<p className="muted">모든 조건이 모이면 모임장이 후보를 만들어요.</p>)}
      {!ready&&<p className="muted">아직 조건을 저장하지 않은 참가자가 있어요.</p>}
      {group.candidates&&<>{group.understood&&<section className="group-card understood"><h3>조건을 이렇게 이해했어요</h3>{group.understood.map(u=>u.private?<p key={u.name}><b>{u.name}</b> 🔒 비밀 조건</p>:<p key={u.name}><b>{u.name}</b> {[u.wants.length&&`원하는 것: ${u.wants.join(', ')}`,u.excludes.length&&`제외: ${u.excludes.join(', ')}`,u.budget&&`예산: ${u.budget.toLocaleString('ko-KR')}원 이하`,u.hour!=null&&`${u.hour}시 방문`].filter(Boolean).join(' · ')||'특별한 조건 없음'}</p>)}<small className="muted">다르게 이해했다면 조건 문장을 고쳐 다시 저장해 주세요.</small></section>}{group.answer&&<p>{group.answer}</p>}<details className="recommendation-info"><summary>추천 정보의 확인 범위</summary><p>{group.notice}</p></details>{!group.candidates.length?<p>현재 정보로 후보를 고르기 어려워요. 조건을 함께 확인해 주세요.</p>:<><h3>{group.members.length===1?'가고 싶은 가게를 선택하세요':'갈 수 있는 곳을 모두 선택하세요'}</h3><p className="muted">{group.members.length===1?'선택하면 바로 결과가 나와요.':'다 고른 뒤 아래 ‘투표 완료’를 눌러 주세요. 모두 완료하면 결과가 공개돼요.'}</p><div className="group-grid">{group.candidates.map(p=>{const selected=group.votes[mine.memberId]?.includes(p.id);return <article key={p.id} className="group-card"><h3>{p.name}</h3><p>{p.kind} · {p.address}<TravelInfo origin={userLocation} place={p}/></p><div className="candidate-reason"><b>후보로 고른 이유</b><p>{p.reason||`등록 업종: ${p.kind}`}</p><p className="candidate-check">{p.checks||'세부 조건은 확인 필요'}</p>{p.status&&<span className="pill">이웃 등록 · 확인 전</span>}</div>{p.memberChecks&&<details className="member-checks"><summary>참가자별 확인 결과</summary>{p.memberChecks.map(m=><div key={m.name}><b>{m.name}</b>{m.private?<p className="muted">🔒 비밀 조건 · {m.checks.map(c=>c.statusLabel).join(', ')||'조건 없음'}</p>:m.checks.length?m.checks.map((c,i)=><p key={i} className={'check-'+c.status}>{c.label} — <strong>{c.statusLabel}</strong><small> {c.evidence}</small></p>):<p>특별한 조건 없음</p>}</div>)}</details>}{p.placeUrl&&<a href={p.placeUrl} target="_blank" rel="noreferrer">가게 정보 확인</a>}{!group.decision&&!group.voting?.allSubmitted&&<button className={'button '+(selected?'dark':'outline')} aria-pressed={!!selected} disabled={busy} onClick={()=>perform(async()=>{const old=group.votes[mine.memberId]||[];const ids=selected?old.filter(id=>id!==p.id):[...old,p.id];const d=await api('/'+active+'/vote','PUT',{ids,revision:group.revision},mine.token);setGroup(d.group);})}>{selected?<><Check size={16}/>선택 취소</>:'이 가게에 투표'}</button>}</article>;})}</div>
        {!group.decision&&!group.voting?.allSubmitted&&<div className="group-vote-stage"><h3>투표 진행</h3><p>{group.voting?.submittedCount||0} / {group.members.length}명 완료 · 갈 수 있는 가게를 모두 고른 뒤 완료를 눌러 주세요.</p>{group.submittedVotes?.[mine.memberId]?<p role="status">내 투표를 완료했어요. 다른 참가자를 기다리는 중이에요. 선택을 바꾸면 다시 완료해야 해요.</p>:<button className="button dark" disabled={busy||!group.votes[mine.memberId]?.length} onClick={()=>perform(async()=>{const d=await api('/'+active+'/vote/submit','POST',{revision:group.revision},mine.token);setGroup(d.group);})}>선택 완료하고 결과 기다리기</button>}</div>}
        {group.voting?.allSubmitted&&<section className="group-vote-results"><h3>투표 결과</h3><p>{group.members.length}명 모두 투표를 마쳤어요.</p>{group.candidates.map(p=><div className="group-result-row" key={p.id}><span>{p.name}</span><strong>{group.voting.counts[p.id]||0}표</strong></div>)}<p className="muted">{group.voting.majorityId?'한 가게가 과반수를 받았어요. 아래 방법으로 최종 결정할 수 있어요.':'과반수를 받은 가게가 없어요. 재투표하거나 룰렛·AI로 정할 수 있어요.'}</p>
        {!group.decision&&(group.ownerId===mine.memberId?<div className="group-final-actions">{group.voting.majorityId?<button className="button lime" disabled={busy} onClick={()=>finalize('majority')}>다수결 결과로 확정</button>:<button className="button outline" disabled={busy} onClick={()=>perform(async()=>{const d=await api('/'+active+'/revote','POST',{},mine.token);setGroup(d.group);})}>재투표</button>}<button className="button outline" disabled={busy} onClick={()=>finalize('roulette')}>랜덤 룰렛 돌리기</button><button className="button outline" disabled={busy} onClick={()=>finalize('ai')}>AI에게 맡기기</button><p className="muted">AI에게 맡기면 참가자 조건과 후보 가게 정보가 OpenRouter로 전송돼요. AI는 투표를 받은 가게 중에서만 골라요.</p></div>:<p className="muted">모임장이 최종 결정 방식을 고르고 있어요.</p>)}
        {spinning&&<div className="group-roulette" role="status"><div className="group-roulette-wheel" aria-hidden="true"/><p>투표받은 가게 중에서 룰렛을 돌리고 있어요…</p></div>}
        {group.decision&&!spinning&&(()=>{const winner=group.candidates.find(p=>p.id===group.decision.placeId);return <div className="group-final-result" role="status"><span className="title-badge">우리의 선택</span><h2>오늘은 {winner?.name||'이 가게'}!</h2><p>{group.decision.reason}</p><small>{group.decision.mode==='majority'?'다수결':group.decision.mode==='roulette'?'랜덤 룰렛':'AI 추천'}으로 결정</small>{winner?.placeUrl&&<a className="button dark" href={winner.placeUrl} target="_blank" rel="noreferrer">카카오맵에서 길 찾기</a>}</div>;})()}</section>}
      </>}</>}
    </section>}
  </div>;
}
