import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,Mic,Send,LogOut} from 'lucide-react';
import './ownerMarketing.css';

const tokenKey='wolgye-owner-session';
async function api(path,{method='GET',body,token,adminKey}={}){const response=await fetch(`/api/owner${path}`,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...(adminKey?{'x-owner-admin-key':adminKey}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'요청에 실패했어요.');return data;}
const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});

export default function OwnerMarketing({places,onBack}){
 const [token,setToken]=useState(()=>localStorage.getItem(tokenKey)||''),[placeId,setPlaceId]=useState(''),[section,setSection]=useState('chat'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[authMode,setAuthMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[choice,setChoice]=useState(''),[adminKey,setAdminKey]=useState(''),[pending,setPending]=useState([]);
 const [adminLoaded,setAdminLoaded]=useState(false);
 const [chat,setChat]=useState([]),[message,setMessage]=useState(''),[recording,setRecording]=useState(false),[brief,setBrief]=useState(''),[format,setFormat]=useState('square'),[proposals,setProposals]=useState([]),[preview,setPreview]=useState({}),[campaigns,setCampaigns]=useState([]),[campaign,setCampaign]=useState({title:'',body:'',status:'draft',proposalId:''}),[report,setReport]=useState(null);
 const recorder=useRef(null),parts=useRef([]),previewUrls=useRef([]);
 const selectedPlace=places.find(p=>p.id===placeId);
 const run=async work=>{setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const load=async current=>{const [me,p,c,r]=await Promise.all([api('/me',{token:current}),api('/proposals',{token:current}),api('/campaigns',{token:current}),api('/report',{token:current})]);setPlaceId(me.placeId);setProposals(p.items);setCampaigns(c.items);setReport(r);};
 useEffect(()=>{if(token)load(token).catch(()=>{localStorage.removeItem(tokenKey);setToken('');});},[token]);
 useEffect(()=>()=>{for(const url of previewUrls.current)URL.revokeObjectURL(url);},[]);
 async function login(e){e.preventDefault();await run(async()=>{const d=await api('/login',{method:'POST',body:{email,password}});localStorage.setItem(tokenKey,d.token);setToken(d.token);setPassword('');});}
 async function register(e){e.preventDefault();await run(async()=>{await api('/register',{method:'POST',body:{placeId:choice,email,password}});setPassword('');setNotice('가입 신청을 받았어요. 관리자 승인 후 로그인할 수 있습니다.');setAuthMode('login');});}
 async function send(e){e.preventDefault();const text=message.trim();if(!text)return;await run(async()=>{const d=await api('/chat',{method:'POST',token,body:{message:text,history:chat.map(x=>({role:x.role,content:x.content}))}});setChat(x=>[...x,{role:'user',content:text},{role:'assistant',content:d.reply}]);setMessage('');});}
 async function toggleRecord(){if(recording){recorder.current?.stop();setRecording(false);return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError('이 브라우저에서 녹음할 수 없어요. 보안 연결(HTTPS)인지 확인해 주세요.');return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);recorder.current=r;parts.current=[];r.ondataavailable=e=>parts.current.push(e.data);r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(parts.current,{type:r.mimeType||'audio/webm'});if(blob.size>4_000_000){setError('녹음이 너무 길어요. 4MB 이하로 다시 녹음해 주세요.');return;}await run(async()=>{const audio=await readFile(blob),d=await api('/transcribe',{method:'POST',token,body:{audio,mime:blob.type}});setMessage(m=>[m,d.text].filter(Boolean).join(' '));});};r.start();setRecording(true);}catch(e){setError(e.message||'마이크 사용 권한을 확인해 주세요.');}}
 async function generate(e){e.preventDefault();await run(async()=>{const d=await api('/proposals',{method:'POST',token,body:{brief,format}});setProposals((await api('/proposals',{token})).items);setBrief('');setNotice('이미지와 문안을 만들었어요. 내용을 검토한 뒤 승인해 주세요.');await showImage(d.id);});}
 async function showImage(id){if(preview[id])return;const r=await fetch(`/api/owner/proposals/${id}/image`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('이미지를 불러오지 못했어요.');const url=URL.createObjectURL(await r.blob());previewUrls.current.push(url);setPreview(x=>({...x,[id]:url}));}
 async function review(id,status){await run(async()=>{await api(`/proposals/${id}`,{method:'PATCH',token,body:{status}});setProposals((await api('/proposals',{token})).items);});}
 async function saveCampaign(e){e.preventDefault();await run(async()=>{await api('/campaigns',{method:'POST',token,body:campaign});setCampaigns((await api('/campaigns',{token})).items);setCampaign({title:'',body:'',status:'draft',proposalId:''});setNotice('캠페인을 저장했어요.');});}
 async function removeCampaign(id){if(!window.confirm('이 캠페인을 삭제할까요?'))return;await run(async()=>{await api(`/campaigns/${id}`,{method:'DELETE',token});setCampaigns((await api('/campaigns',{token})).items);});}
 async function refreshAdmin(){setAdminLoaded(false);setPending([]);await run(async()=>{setPending((await api('/admin/requests',{adminKey})).items);setAdminLoaded(true);});}
 async function decide(id,approve){await run(async()=>{await api(`/admin/requests/${id}`,{method:'POST',adminKey,body:{approve}});setPending((await api('/admin/requests',{adminKey})).items);});}
 const chart=(title,values)=> <div className="owner-chart"><h3>{title}</h3>{Object.entries(values||{}).sort((a,b)=>b[1]-a[1]).map(([label,count])=><div className="owner-bar" key={label}><span>{label}</span><div><i style={{width:`${Math.max(3,100*count/(report?.totalViews||1))}%`}}/></div><b>{count}</b></div>)}</div>;
 return <div className="owner-page"><button className="text-link" onClick={onBack}><ArrowLeft size={18}/> 월계밥상으로</button><div className="page-heading"><div><span className="eyebrow">FOR OUR LOCAL OWNERS</span><h1>가게를 알리는 공간<span className="lime-period">.</span></h1><p>사장님이 직접 확인하고 전하는 이야기</p></div></div>
 {!token?<div className="owner-card owner-auth"><div className="owner-tabs"><button className={authMode==='login'?'active':''} onClick={()=>setAuthMode('login')}>로그인</button><button className={authMode==='register'?'active':''} onClick={()=>setAuthMode('register')}>사장님 가입 신청</button><button className={authMode==='admin'?'active':''} onClick={()=>setAuthMode('admin')}>관리자 승인</button></div>{authMode==='admin'?<><p>관리자만 승인 대기 계정을 확인할 수 있습니다.</p><form className="owner-admin-form" onSubmit={e=>{e.preventDefault();refreshAdmin();}}><label>관리자 키<input type="password" value={adminKey} onChange={e=>{setAdminKey(e.target.value);setAdminLoaded(false);setPending([]);}}/></label><button type="submit" className="button dark" disabled={busy||!adminKey.trim()}>{busy?'확인 중…':'신청 확인'}</button></form>{adminLoaded&&<p className="owner-admin-result" role="status">{pending.length?`승인 대기 신청 ${pending.length}건이 있어요.`:'현재 승인 대기 중인 신청이 없어요.'}</p>}{pending.map(a=><article className="owner-list-item" key={a.id}><b>{a.email}</b><p>{places.find(p=>p.id===a.placeId)?.name||a.placeId}</p><button onClick={()=>decide(a.id,true)}>승인</button><button onClick={()=>decide(a.id,false)}>거절</button></article>)}</>:<form onSubmit={authMode==='login'?login:register}>{authMode==='register'&&<label>내 가게<select required value={choice} onChange={e=>setChoice(e.target.value)}><option value="">가게 선택</option>{places.map(p=><option key={p.id} value={p.id}>{p.name} · {p.address}</option>)}</select></label>}<label>이메일<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>비밀번호<input type="password" minLength={authMode==='register'?8:1} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button dark" disabled={busy}>{authMode==='login'?'로그인':'가입 신청'}</button>{authMode==='register'&&<p className="muted">실제 가게 소유 여부를 관리자가 확인한 뒤 승인합니다.</p>}</form>}</div>:<><div className="owner-identity"><b>{selectedPlace?.name||'내 가게'}</b><button className="text-link" onClick={()=>{api('/logout',{method:'POST',token}).catch(()=>{});localStorage.removeItem(tokenKey);setToken('');setPlaceId('');}}><LogOut size={17}/> 로그아웃</button></div><div className="owner-tabs">{[['chat','AI 홍보 대화'],['proposals','콘텐츠 제안 검토'],['campaigns','캠페인 관리'],['report','성과 리포트']].map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}>{label}</button>)}</div>
 {section==='chat'&&<section className="owner-card"><h2>AI 홍보 대화</h2><p className="muted">가게를 어떻게 알릴지 이야기해 보세요. 마이크로 녹음하면 STT 모델이 글로 바꿉니다.</p><div className="owner-chat">{chat.length?chat.map((x,i)=><p key={i} className={x.role}>{x.content}</p>):<p className="muted">예: 점심 손님에게 우리 가게를 어떻게 소개할까?</p>}</div><form className="owner-chat-form" onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} maxLength={1000} placeholder="홍보 고민을 적어 주세요"/><button type="button" className="button outline" onClick={toggleRecord} aria-label={recording?'녹음 끝내기':'녹음 시작'}>{recording?'녹음 끝내기':<Mic size={18}/>}</button><button className="button dark" disabled={busy||!message.trim()}><Send size={17}/> 보내기</button></form></section>}
 {section==='proposals'&&<section className="owner-card"><h2>콘텐츠 제안 검토</h2><p className="muted">AI가 문안과 이미지를 제안합니다. 사실관계를 확인하고 승인한 것만 캠페인에 연결하세요.</p><form onSubmit={generate}><label>어떤 홍보 콘텐츠가 필요하신가요?<textarea required maxLength={1000} value={brief} onChange={e=>setBrief(e.target.value)} placeholder="예: 비 오는 날 따뜻한 점심 메뉴 분위기를 알리고 싶어요"/></label><label>이미지 형태<select value={format} onChange={e=>setFormat(e.target.value)}><option value="square">정사각형</option><option value="portrait">세로형</option></select></label><button className="button dark" disabled={busy||!brief.trim()}>{busy?'AI가 만드는 중…':'문안과 이미지 생성'}</button></form><div className="owner-list">{proposals.map(p=><article className="owner-list-item" key={p.id}><small>{new Date(p.createdAt).toLocaleDateString('ko-KR')} · {p.status==='review'?'검토 중':p.status==='approved'?'승인':'거절'}</small><p>{p.copy}</p>{preview[p.id]?<img className="owner-generated" src={preview[p.id]} alt="AI가 생성한 홍보 이미지"/>:<button className="text-link" onClick={()=>run(()=>showImage(p.id))}>이미지 보기</button>}{p.status==='review'&&<div className="owner-actions"><button className="button lime" onClick={()=>review(p.id,'approved')}>내용 확인 후 승인</button><button className="button outline" onClick={()=>review(p.id,'rejected')}>사용하지 않기</button></div>}</article>)}</div></section>}
 {section==='campaigns'&&<section className="owner-card"><h2>사장님 캠페인</h2><p className="muted">이웃 누구나 쓰는 ‘소식’과 별개로, 승인받은 사장님 계정만 게시합니다.</p><form onSubmit={saveCampaign}><label>제목<input required maxLength={100} value={campaign.title} onChange={e=>setCampaign(x=>({...x,title:e.target.value}))}/></label><label>내용<textarea required maxLength={1500} value={campaign.body} onChange={e=>setCampaign(x=>({...x,body:e.target.value}))}/></label><label>승인된 이미지 제안<select value={campaign.proposalId} onChange={e=>setCampaign(x=>({...x,proposalId:e.target.value}))}><option value="">이미지 없이 게시</option>{proposals.filter(p=>p.status==='approved').map(p=><option key={p.id} value={p.id}>{p.copy.slice(0,40)}</option>)}</select></label><label>공개 상태<select value={campaign.status} onChange={e=>setCampaign(x=>({...x,status:e.target.value}))}><option value="draft">임시 저장</option><option value="published">게시</option></select></label><button className="button dark" disabled={busy}>저장</button></form><div className="owner-list">{campaigns.map(c=><article className="owner-list-item" key={c.id}><small>{c.status==='published'?'게시 중':'임시 저장'} · {new Date(c.updatedAt).toLocaleDateString('ko-KR')}</small><h3>{c.title}</h3><p>{c.body}</p><div className="owner-actions"><button className="button outline" onClick={()=>setCampaign({id:c.id,title:c.title,body:c.body,status:c.status,proposalId:c.proposalId||''})}>수정</button><button className="button outline" onClick={()=>removeCampaign(c.id)}>삭제</button></div></article>)}</div></section>}
 {section==='report'&&<section className="owner-card"><h2>성과 리포트</h2><p className="muted">{report?.period||'조회 기록을 불러오고 있어요.'} · 실제 매장 방문이나 매출 전환은 측정하지 않습니다.</p><button className="text-link" onClick={()=>run(async()=>setReport(await api('/report',{token})))}>새로고침</button><div className="owner-total"><b>{report?.totalViews??0}</b><span>가게 상세 조회</span></div><p className="muted">연령·성별·인원·예산·식사 시간은 이용자가 자발적으로 입력한 값만 집계하며 미입력은 ‘미응답’입니다.</p>{chart('연령',report?.age)}{chart('성별',report?.gender)}{chart('인원 수',report?.people)}{chart('원하는 금액 (원)',report?.budget)}{chart('원하는 식사 시간',report?.mealTime)}</section>}
 </>}{error&&<p className="notice" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}</div>;
}
