import React,{useEffect,useState} from 'react';

async function record(placeId,details){const response=await fetch(`/api/owner/views/${encodeURIComponent(placeId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({details})});if(!response.ok)throw new Error('조회 정보를 반영하지 못했어요.');}
// 로그인한 이용자가 프로필에 연령대·성별을 남겼다면 그 값만 함께 보낸다(서버가 허용된 값만 저장).
export function recordPlaceView(placeId,profile){record(placeId,profile?{age:profile.ageGroup||undefined,gender:profile.gender||undefined}:undefined).catch(()=>{});}

export default function PlaceMarketing({placeId}){
 const [items,setItems]=useState([]),[open,setOpen]=useState(false),[thanks,setThanks]=useState(false),[details,setDetails]=useState({age:'',gender:'',people:'',budget:'',mealTime:''});
 useEffect(()=>{let live=true;fetch(`/api/owner/campaigns/${encodeURIComponent(placeId)}`).then(r=>r.json()).then(d=>{if(live)setItems(d.items||[]);}).catch(()=>{});return()=>{live=false;};},[placeId]);
 async function submit(e){e.preventDefault();try{await record(placeId,details);setThanks(true);setOpen(false);}catch{setThanks(false);}}
 return <><h3>사장님이 전하는 캠페인</h3>{items.length?items.map(c=><article className="place-update" key={c.id}><b>{c.title}</b><p>{c.body}</p><small>사장님 계정에서 게시 · {new Date(c.updatedAt).toLocaleDateString('ko-KR')}</small>{c.proposalId&&<img className="upload-preview" src={`/api/owner/campaigns/${encodeURIComponent(placeId)}/${c.id}/image`} alt="사장님이 승인한 AI 홍보 이미지"/>}</article>):<p className="muted">아직 사장님 캠페인이 없어요.</p>}<div className="place-update"><b>이 가게 조회 통계에 참여하기</b><p>아래 항목은 선택 사항이에요. 입력한 답은 사장님에게 집계로만 보이고, 입력하지 않은 항목은 미응답으로 표시됩니다.</p>{thanks?<p role="status">응답을 반영했어요. 고맙습니다.</p>:<button className="text-link" onClick={()=>setOpen(v=>!v)}>{open?'닫기':'선택 항목 입력'}</button>}{open&&<form className="place-stats-form" onSubmit={submit}><label>연령대<select value={details.age} onChange={e=>setDetails(x=>({...x,age:e.target.value}))}><option value="">미응답</option>{['10대','20대','30대','40대','50대 이상'].map(x=><option key={x}>{x}</option>)}</select></label><label>성별<select value={details.gender} onChange={e=>setDetails(x=>({...x,gender:e.target.value}))}><option value="">미응답</option>{['여성','남성','기타'].map(x=><option key={x}>{x}</option>)}</select></label><label>함께 식사할 인원<input type="number" min="1" max="20" value={details.people} onChange={e=>setDetails(x=>({...x,people:e.target.value}))} placeholder="선택"/></label><label>1인당 원하는 금액 (원)<input type="number" min="1000" max="100000" step="1000" value={details.budget} onChange={e=>setDetails(x=>({...x,budget:e.target.value}))} placeholder="선택"/></label><label>식사 시간<select value={details.mealTime} onChange={e=>setDetails(x=>({...x,mealTime:e.target.value}))}><option value="">미응답</option>{['아침','점심','저녁','야식'].map(x=><option key={x}>{x}</option>)}</select></label><button className="button outline">집계에 반영</button></form>}</div></>;
}
