import {textModel} from './services/llm.js';
import {authenticate,requireUser,requireAdmin} from './auth.js';
import express from 'express';
import {randomUUID} from 'node:crypto';
import {getCommunityPlaces} from './services/communityService.js';
import {ownerMarketingStore as store} from './services/ownerMarketingStore.js';

export function createOwnerMarketingRouter(){
  const router=express.Router();
  const secret=()=>process.env.OPENROUTER_API_KEY?.trim();
  const owner=async(req,res,next)=>{if(!req.user)return res.status(401).json({error:'로그인해 주세요.'});const a=(await store.accountForUser(req.user.id));if(a?.status!=='approved')return res.status(403).json({error:'가게 관리 권한 승인 후 이용할 수 있어요.'});req.owner={placeId:a.placeId};next();};
  const admin=requireAdmin;
  for(const method of ['get','post','patch','delete']){const original=router[method].bind(router);router[method]=(route,...handlers)=>original(route,...handlers.map(h=>(req,res,next)=>Promise.resolve().then(()=>h(req,res,next)).catch(e=>res.headersSent?next(e):failure(res,e))));}
  router.use(authenticate);
  const placeExists=async id=>(await getCommunityPlaces()).items.some(p=>p.id===id);
  const clean=(v,max)=>typeof v==='string'?v.trim().slice(0,max):'';
  const attempts=new Map();
  const limit=(max,period=60000)=>async(req,res,next)=>{const key=`${req.ip}:${req.path}`,now=Date.now(),row=attempts.get(key);if(!row||row.until<now){attempts.set(key,{count:1,until:now+period});return next();}if(row.count++>=max)return res.status(429).json({error:'요청이 많아요. 잠시 후 다시 시도해 주세요.'});next();};
  const ai=async(path,body,asForm=false)=>{if(!secret())throw Object.assign(new Error('OPENROUTER_API_KEY 설정이 필요해요.'),{status:503});const response=await fetch(`https://openrouter.ai/api/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${secret()}`,...(asForm?{}:{'Content-Type':'application/json'})},body:asForm?body:JSON.stringify(body),signal:AbortSignal.timeout(path==='images'?120000:60000)});const json=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(json.error?.message||'AI 요청에 실패했어요.'),{status:502});return json;};
  const failure=(res,e)=>res.status(e.status||500).json({error:e.name==='TimeoutError'?'AI 응답이 지연되고 있어요. 다시 시도해 주세요.':e.message});

  router.post('/register',requireUser,limit(5,3600000),async(req,res)=>{try{const placeId=clean(req.body?.placeId,120);if(!placeId||!await placeExists(placeId))return res.status(400).json({error:'등록된 가게를 선택해 주세요.'});if(!(await store.requestUserAccount(placeId,req.user)))return res.status(409).json({error:'이미 신청 중이거나 승인된 가게가 있어요.'});res.status(201).json({status:'pending'});}catch(e){failure(res,e);}});
  router.get('/admin/requests',admin,async(req,res)=>res.json({items:(await store.pendingAccounts())}));
  router.post('/admin/requests/:id',admin,async(req,res)=>{if(typeof req.body?.approve!=='boolean')return res.status(400).json({error:'approve 값을 지정해 주세요.'});res.status((await store.approveAccount(req.params.id,req.body.approve))?200:404).json({ok:true});});


  router.get('/me',requireUser,async(req,res)=>{const a=(await store.accountForUser(req.user.id));res.json({placeId:a?.status==='approved'?a.placeId:null,status:a?.status||'none',aiReady:!!secret()});});
  router.get('/campaigns/:placeId',async(req,res)=>{try{if(!await placeExists(req.params.placeId))return res.status(404).json({error:'가게를 찾지 못했어요.'});res.json({items:(await store.publicCampaigns(req.params.placeId))});}catch(e){failure(res,e);}});
  router.get('/campaigns',owner,async(req,res)=>res.json({items:(await store.campaigns(req.owner.placeId))}));
  router.post('/campaigns',owner,async(req,res)=>{const title=clean(req.body?.title,100),body=clean(req.body?.body,1500),status=req.body?.status==='published'?'published':'draft',proposalId=clean(req.body?.proposalId,100);if(!title||!body)return res.status(400).json({error:'제목과 내용을 입력해 주세요.'});if(proposalId&&!(await store.proposals(req.owner.placeId)).some(p=>p.id===proposalId&&p.status==='approved'))return res.status(400).json({error:'승인한 콘텐츠만 캠페인에 연결할 수 있어요.'});const row=(await store.saveCampaign(req.owner.placeId,{title,body,status,proposalId},clean(req.body?.id,100)||undefined));if(!row)return res.status(404).json({error:'캠페인을 찾지 못했어요.'});res.json(row);});
  router.delete('/campaigns/:id',owner,async(req,res)=>res.status((await store.removeCampaign(req.owner.placeId,req.params.id))?200:404).json({ok:true}));
  router.get('/proposals',owner,async(req,res)=>res.json({items:(await store.proposals(req.owner.placeId)).map(({image,...p})=>({...p,hasImage:!!image}))}));
  router.get('/proposals/:id/image',owner,async(req,res)=>{const p=(await store.proposals(req.owner.placeId)).find(x=>x.id===req.params.id);if(!p?.image)return res.status(404).end();res.type('png').send(Buffer.from(p.image,'base64'));});
  router.get('/campaigns/:placeId/:id/image',async(req,res)=>{const c=(await store.publicCampaigns(req.params.placeId)).find(x=>x.id===req.params.id),p=(await store.proposals(req.params.placeId)).find(x=>x.id===c?.proposalId&&x.status==='approved');if(!p?.image)return res.status(404).end();res.type('png').send(Buffer.from(p.image,'base64'));});
  router.patch('/proposals/:id',owner,async(req,res)=>{const status=req.body?.status;if(!['approved','rejected'].includes(status))return res.status(400).json({error:'검토 상태가 올바르지 않아요.'});const row=(await store.reviewProposal(req.owner.placeId,req.params.id,status));if(!row)return res.status(404).json({error:'제안을 찾지 못했어요.'});res.json({id:row.id,status:row.status});});
  router.post('/chat',owner,limit(12),async(req,res)=>{const message=clean(req.body?.message,1000),history=Array.isArray(req.body?.history)?req.body.history.slice(-8).filter(x=>['user','assistant'].includes(x.role)&&typeof x.content==='string').map(x=>({role:x.role,content:x.content.slice(0,1000)})):[];if(!message)return res.status(400).json({error:'대화 내용을 입력해 주세요.'});try{const data=await ai('chat/completions',{model:process.env.OWNER_TEXT_MODEL||textModel(),temperature:0.7,max_tokens:600,messages:[{role:'system',content:'당신은 월계1동 식당 사장님을 돕는 홍보 조언자입니다. 사실이 확인되지 않은 가격, 할인, 영업시간, 리뷰, 고객 반응은 지어내지 마세요. 한국어로 짧고 실용적으로 답하고, 게시 전 사장님 확인이 필요한 사항을 알려주세요.'},...history,{role:'user',content:message}]});res.json({reply:data.choices?.[0]?.message?.content||'답변을 받지 못했어요.'});}catch(e){failure(res,e);}});
  router.post('/transcribe',owner,limit(12),async(req,res)=>{const audio=req.body?.audio,mime=clean(req.body?.mime,80),match=typeof audio==='string'&&audio.match(/^data:audio\/(webm|mp4|mpeg|ogg|wav)(?:;[^,]+)*;base64,/);if(!match||audio.length>6_000_000)return res.status(400).json({error:'5MB 이하의 녹음 파일을 보내 주세요.'});try{const base64=audio.split(',')[1],form=new FormData();form.append('file',new Blob([Buffer.from(base64,'base64')],{type:mime||`audio/${match[1]}`}),`recording.${match[1]}`);form.append('model',process.env.OWNER_STT_MODEL||'openai/gpt-4o-mini-transcribe');form.append('language','ko');const data=await ai('audio/transcriptions',form,true);res.json({text:data.text||''});}catch(e){failure(res,e);}});
  router.post('/proposals',owner,limit(4,3600000),async(req,res)=>{const brief=clean(req.body?.brief,1000),format=req.body?.format;if(!brief||!['square','portrait'].includes(format))return res.status(400).json({error:'홍보 목적과 이미지 형태를 선택해 주세요.'});try{const place=(await getCommunityPlaces()).items.find(p=>p.id===req.owner.placeId);const prompt=`월계밥상 식당 홍보용 사진 스타일 이미지. 가게: ${place?.name||'동네 식당'}. 사장님 요청: ${brief}. 실제 가게의 외관, 로고, 메뉴 가격, 할인 혜택, 사람 얼굴 등 확인되지 않은 구체적 사실은 표현하지 말고, 텍스트 없는 음식 분위기 이미지로 제작.`;const [copy,image]=await Promise.all([ai('chat/completions',{model:process.env.OWNER_TEXT_MODEL||textModel(),max_tokens:400,messages:[{role:'system',content:'사장님 검토용 홍보 문안을 한국어로 2~3문장 작성하세요. 확인되지 않은 사실은 만들지 마세요.'},{role:'user',content:`가게: ${place?.name||''}. 요청: ${brief}`}] }),ai('images',{model:process.env.OWNER_IMAGE_MODEL||'openai/gpt-image-1-mini',prompt,quality:'low',aspect_ratio:format==='portrait'?'2:3':'1:1'})]);const b64=image.data?.[0]?.b64_json;if(!b64)throw new Error('이미지가 생성되지 않았어요.');const row=(await store.saveProposal(req.owner.placeId,{brief,format,copy:copy.choices?.[0]?.message?.content||'',image:b64}));res.json({id:row.id,copy:row.copy,status:row.status,hasImage:true});}catch(e){failure(res,e);}});
  router.post('/views/:placeId',limit(100,3600000),async(req,res)=>{try{const id=req.params.placeId;if(!await placeExists(id))return res.status(404).json({error:'가게를 찾지 못했어요.'});let viewer=(req.get('cookie')||'').match(/(?:^|;\s*)wolgye_viewer=([a-f0-9-]{36})(?:;|$)/)?.[1];if(!viewer){viewer=randomUUID();res.cookie('wolgye_viewer',viewer,{httpOnly:true,sameSite:'lax',maxAge:90*86400000,secure:req.secure});}(await store.recordView(id,viewer,req.body?.details||{}));res.json({ok:true});}catch(e){failure(res,e);}});
  router.get('/report',owner,async(req,res)=>res.json((await store.report(req.owner.placeId))));
  return router;
}
